# Important Notes:
# Every field you add must be added to build-logic/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.1
group=com.example.uselocalrecipes
java_version=25

# Common
minecraft_version=26.3
mod_name=Use Local Recipes
mod_author=link-fgfgui
mod_id=uselocalrecipes
license=MIT
credits=Inspired by EMI's client recipe loader
description=Reads recipes from local game/mod files and feeds them to client recipe viewers when the server does not sync recipes.
minecraft_version_range=[26.3, 26.4)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.160.6+26.3
fabric_loader_version=0.19.5
# JEI, see https://maven.blamejared.com/mezz/jei/ (must exist for the targeted minecraft_version)
jei_version=31.0.0.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.3.0.1-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
